# Generated by Django 4.2.1 on 2023-05-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('email', models.CharField(default='-', max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('user_id', models.CharField(max_length=20)),
                ('user_pw', models.CharField(max_length=20)),
            ],
        ),
    ]
