# Generated by Django 4.2.1 on 2023-05-23 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField(unique=True)),
                ('action_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.actionbox')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.player')),
            ],
        ),
    ]
