# Generated by Django 4.1.5 on 2023-05-08 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_num', models.IntegerField(default=2)),
                ('baby_num', models.IntegerField(default=0)),
                ('fst_player', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(default='-', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_id',
            field=models.CharField(default='-', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='user_pw',
            field=models.CharField(default='-', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PlayerBoardStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(default='나무', max_length=2)),
                ('room_num', models.IntegerField(default=2)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.account'),
        ),
    ]
