# Generated by Django 4.1.5 on 2023-05-08 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_player_remove_account_id_alter_account_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('position_name', models.CharField(default='빈칸', max_length=6)),
                ('is_fam', models.BooleanField(default=False)),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.playerboardstatus')),
            ],
        ),
    ]
