# Generated by Django 4.2.1 on 2023-05-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_familyposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField(default=1)),
            ],
        ),
    ]
