# Generated by Django 4.2.1 on 2023-06-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_playerboardstatus_fence_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionbox',
            name='acc_resource',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='actionbox',
            name='add_resource',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
