# Generated by Django 4.2.1 on 2023-06-06 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_playerboardstatus_fence_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activate', models.IntegerField(default=0)),
                ('card_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameplay.card')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.player')),
            ],
        ),
    ]
