# Generated by Django 4.2.1 on 2023-06-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_gamestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionbox',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
