# Generated by Django 4.2.1 on 2023-06-02 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0004_actionbox_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionbox',
            name='is_res',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='actionbox',
            name='card_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gameplay.periodcard'),
        ),
    ]
