# Generated by Django 4.2.1 on 2023-06-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0005_actionbox_is_res_alter_actionbox_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionbox',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
    ]
