# Generated by Django 4.2.1 on 2023-06-06 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0004_alter_actionbox_acc_resource_and_more'),
        ('gameplay', '0005_playerboardstatus_pen_num'),
    ]

    operations = [
    ]
