# Generated by Django 4.2.1 on 2023-06-06 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0006_merge_20230606_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerboardstatus',
            name='score',
        ),
    ]
