# Generated by Django 4.2.1 on 2023-06-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0007_remove_playerboardstatus_score'),
        ('gameplay', '0007_room'),
    ]

    operations = [
    ]
