# Generated by Django 4.2.1 on 2023-06-07 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0008_merge_0007_remove_playerboardstatus_score_0007_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardposition',
            name='animal_type',
        ),
        migrations.CreateModel(
            name='PenPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.IntegerField(default=0)),
                ('max_num', models.IntegerField(default=2)),
                ('current_num', models.IntegerField(default=0)),
                ('position_list', models.CharField(max_length=100)),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.playerboardstatus')),
            ],
        ),
    ]
