# Generated by Django 4.2.1 on 2023-06-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0009_remove_boardposition_animal_type_penposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='fenceposition',
            name='player_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
