# Generated by Django 4.2.1 on 2023-06-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0010_fenceposition_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainfacilitycard',
            name='player_id',
            field=models.IntegerField(default=0),
        ),
    ]
