# Generated by Django 4.2.1 on 2023-06-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0011_mainfacilitycard_player_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FstPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
            ],
        ),
    ]
