# Generated by Django 4.2.1 on 2023-06-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0012_fstplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberingFence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('fence_info', models.CharField(max_length=300)),
            ],
        ),
    ]
